services:
  backend:
    build:
      context: ./backend
    container_name: teste_de_software_backend
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_teste_de_software
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: teste_de_software_frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
  db:
    image: postgres:14-alpine
    container_name: teste_de_software_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_teste_de_software
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/posgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
